language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-dev --no-interaction

script:
  - phpunit --configuration app/phpunit.xml.dist --no-coverage
